# Generated by Django 3.1.4 on 2020-12-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
